### ISSUE TITLE
Bug: Unable to make migration and initialize

### ISSUE THREAD

**Issue by machikoyasuda** [cal-itp/benefits#1437]
This issue describes what I'm experiencing locally from this PR: https://github.com/cal-itp/benefits/pull/1436

### Summary

Unable to run `bin/makemigrations.sh; bin/init.sh` after simply re-naming a verifier variable. I was able to run `bin/makemigrations.sh; bin/init.sh` successfully when I made another kind of change (removing a verifier from line 278 in 0002_data.py) though. 

The error message complains about an error in this file: https://github.com/cal-itp/benefits/blob/dev/benefits/core/migrations/sample_agency.json but it hasn't been changed. So I'm not sure where else the error could be.

### Steps to reproduce

1. Rename `mst_courtesy_card_verifier` to `mst_veteran_verifier` in 2 spots in `benefits/core/migrations/0002_data.py`

<details>
    <summary>See the full diff:</summary>
    
```diff
calitp@cdbe8faf8c05:~/app$ git diff
diff --git a/benefits/core/migrations/0001_initial.py b/benefits/core/migrations/0001_initial.py
index 00ed6411..de69f1fb 100644
--- a/benefits/core/migrations/0001_initial.py
+++ b/benefits/core/migrations/0001_initial.py
@@ -1,4 +1,4 @@
-# Generated by Django 4.1.5 on 2023-01-11 23:23
+# Generated by Django 4.2 on 2023-06-21 00:07
 
 from django.db import migrations, models
 import django.db.models.deletion
diff --git a/benefits/core/migrations/0002_data.py b/benefits/core/migrations/0002_data.py
index ef6eaea2..a2c3df59 100644
--- a/benefits/core/migrations/0002_data.py
+++ b/benefits/core/migrations/0002_data.py
@@ -155,7 +155,7 @@ PEM DATA
         enrollment_success_expiry_item_details=None,
     )--
 
-    mst_courtesy_card_verifier = EligibilityVerifier.objects.create(
+    mst_veteran_verifier = EligibilityVerifier.objects.create(
         name=os.environ.get("COURTESY_CARD_VERIFIER", "Eligibility Server Verifier"),
         api_url=os.environ.get("COURTESY_CARD_VERIFIER_API_URL", "http://server:8000/verify"),
         api_auth_header=os.environ.get("COURTESY_CARD_VERIFIER_API_AUTH_HEADER", "X-Server-API-Key"),
@@ -276,7 +276,7 @@ PEM DATA
         eligibility_index_intro=_("eligibility.pages.index.p[0].mst"),
     )
     mst_agency.eligibility_types.set([mst_senior_type, mst_courtesy_card_type])
-    mst_agency.eligibility_verifiers.set([mst_oauth_claims_verifier, mst_courtesy_card_verifier])
+    mst_agency.eligibility_verifiers.set([mst_oauth_claims_verifier, mst_veteran_verifier])
 
     sacrt_agency = TransitAgency.objects.create(
         slug="sacrt"
```
</details>

2. Run `bin/makemigrations.sh; bin/init.sh`
3. I expect this migration to run successfully. I expect an error message to tell me where the error is. 

I am, however, currently getting this error message:
```python
  File "/home/calitp/app/benefits/core/migrations/0002_data.py", line 261, in load_data
    sample_agency = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 232)
```

Full stacktrace:
```
calitp@cdbe8faf8c05:~/app$ bin/makemigrations.sh; bin/init.sh
+ mkdir -p benefits/core/old_migrations
+ mv benefits/core/migrations/0001_initial.py benefits/core/migrations/0002_data.py benefits/core/migrations/__init__.py benefits/core/migrations/sample_agency.json benefits/core/old_migrations
+ cp benefits/core/old_migrations/__init__.py benefits/core/migrations
+ python manage.py makemigrations
Migrations for 'core':
  benefits/core/migrations/0001_initial.py
    - Create model AuthProvider
    - Create model EligibilityType
    - Create model EligibilityVerifier
    - Create model PaymentProcessor
    - Create model PemData
    - Create model TransitAgency
    - Add field client_cert to paymentprocessor
    - Add field client_cert_private_key to paymentprocessor
    - Add field client_cert_root_ca to paymentprocessor
    - Add field public_key to eligibilityverifier
+ cp benefits/core/old_migrations/0001_initial.py benefits/core/old_migrations/0002_data.py benefits/core/old_migrations/__init__.py benefits/core/old_migrations/sample_agency.json benefits/core/migrations --no-clobber --recursive
+ rm -rf benefits/core/old_migrations
+ python -m black benefits/core/migrations/0001_initial.py benefits/core/migrations/0002_data.py benefits/core/migrations/__init__.py benefits/core/migrations/sample_agency.json
All done! ✨ 🍰 ✨
4 files left unchanged.
+ rm -f django.db
+ python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, core, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying core.0001_initial... OK
  Applying core.0002_data...Traceback (most recent call last):
  File "/home/calitp/app/manage.py", line 21, in <module>
    main()
  File "/home/calitp/app/manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/home/calitp/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/home/calitp/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/home/calitp/.local/lib/python3.10/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/home/calitp/.local/lib/python3.10/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/home/calitp/.local/lib/python3.10/site-packages/django/db/migrations/operations/special.py", line 193, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/home/calitp/app/benefits/core/migrations/0002_data.py", line 261, in load_data
    sample_agency = json.load(f)
  File "/usr/local/lib/python3.10/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.10/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 9 column 1 (char 232)
```

**Comment by machikoyasuda** [comment]
One thing I noticed is that when I run `bin/makemigrations.sh`, the `python -m black` command reformats `benefits/core/migrations/sample_agency.json` to have a trailing comma.

```bash
+ python -m black benefits/core/migrations/0001_initial.py benefits/core/migrations/0002_data.py benefits/core/migrations/__init__.py benefits/core/migrations/sample_agency.json
reformatted benefits/core/migrations/sample_agency.json

All done! ✨ 🍰 ✨
1 file reformatted, 3 files left unchanged.
```

But, the VS Code linter does not like this:
<img width="671" alt="image" src="https://github.com/cal-itp/benefits/assets/3673236/592aaf67-4952-4f9c-8946-d3b25d72af21">

**Comment by machikoyasuda** [comment]
When I run `bin/init.sh` _without_ running `bin/makemigrations.sh` (while ensuring that there are no changes to `sample_agency.json`), I am able to run the commands successfully. Deleting the trailing comma in `sample_agency.json` in between the two commands also allows me to run `init.sh` successfully. So I think there's a mismatch between `python black` and Prettier (maybe?) or some other linting tool that's adding a trailing comma in the JSON file that the app actually doesn't like.

**Comment by angela-tran** [comment]
As you noted @machikoyasuda , the problem is because `black` is formatting the JSON file as if it were Python code. I suggest we add `.py` to the glob pattern in `bin/makemigrations.sh` so that the command only formats .py files.
