### ISSUE TITLE
Refactor start page context creation

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#439]
I got a strange error on the Start page:

```
Traceback (most recent call last):
  File "/home/calitp/.local/lib/python3.9/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/calitp/.local/lib/python3.9/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/calitp/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/calitp/.local/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/calitp/app/benefits/eligibility/views.py", line 127, in start
    ctx["media"].insert(0, auth_media)

Exception Type: UnboundLocalError at /eligibility/start
Exception Value: local variable 'auth_media' referenced before assignment
```

Maybe now that the media list refactor and the login button are merged into dev, we can clean up the logic and context creation for this view?

## Steps to recreate

1. From start page, click "Continue with Login.gov" button
2. Sign in with Login.gov account
3. Land on confirm page (DMV form)
4. Change URL manually to `/eligibility` (the verifier select page)
5. Select "Senior Discount Program", click "Continue"
6. 💥

**Comment by thekaveman** [comment]
More info on how to recreate this bug:

1. From start page, click "Continue with Login.gov" button
2. Sign in with Login.gov account
3. Land on confirm page (DMV form)
4. Change URL manually to `/eligibility` (the verifier select page)
5. Select "Senior Discount Program", click "Continue"
6. 💥
