### ISSUE TITLE
Get Azure exception monitoring working again

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/benefits#861]
This is happening on `dev-benefits.calitp.org`

```
2022-08-11T20:28:44.989662609Z [11/Aug/2022 20:28:44] ERROR django.request:241 Internal Server Error: /
2022-08-11T20:28:44.989680509Z Traceback (most recent call last):
2022-08-11T20:28:44.989686609Z   File "/home/calitp/.local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 55, in inner
2022-08-11T20:28:44.989691709Z     response = get_response(request)
2022-08-11T20:28:44.989696209Z   File "/home/calitp/.local/lib/python3.10/site-packages/django/utils/deprecation.py", line 131, in __call__
2022-08-11T20:28:44.989701009Z     if self._is_coroutine:
2022-08-11T20:28:44.989705509Z AttributeError: 'OpencensusMiddleware' object has no attribute '_is_coroutine'
2022-08-11T20:28:44.991650505Z  - - [11/Aug/2022:20:28:44 +0000] "GET / HTTP/1.0" 500 8269 "-" "AlwaysOn"
```

We merged a patch update for `opencensus-ext-azure` in #850. ~Thinking we'll need to revert.~

## To Reproduce

1. Go to https://dev-benefits.calitp.org
2. Observe "Service is down" message
3. Review logs, see above message

**Comment by thekaveman** [comment]
Strange that this is not happening in `test-benefits.calitp.org`, which also got the same update from #850 when we deployed to `test` with #854

**Comment by angela-tran** [comment]
> Strange that this is not happening in `test-benefits.calitp.org`, which also got the same update from #850 when we deployed to `test` with #854

I think I found why it didn't happen in `test-benefits`: https://github.com/cal-itp/benefits/blob/dev/benefits/settings.py#L74-L76
`ENABLE_AZURE_INSIGHTS` is false with the current `test` slot configuration.

**Comment by thekaveman** [comment]
Yep just noticed this, we don't have any of the `INSIGHTS` settings configured in `test`:

![image](https://user-images.githubusercontent.com/1783439/184240775-2cef0a26-44bb-4cc1-887a-9a023d68b6c2.png)

**Comment by thekaveman** [comment]
Removed the `APPLICATIONINSIGHTS_CONNECTION_STRING` from the `dev` and `prod` slots for now, in order to get the app live. Kept a back up locally.

**Comment by afeld** [comment]
Looks like the fix was released: https://github.com/census-instrumentation/opencensus-python/pull/1159#issuecomment-1281264776

**Comment by afeld** [comment]
Made the title more generic, as the idea was raised to re-explore using the Sentry instance being leveraged by the data team (instead of OpenCensus + Azure Monitor).

**Comment by afeld** [comment]
The options going forward are that we can use Azure Monitor and/or Sentry for error monitoring. One is probably fine long-term, but we could keep both (at least for now) to see how we like them side by side.

My early reactions are that Sentry has a lot more features / gives a lot more out of the box around error monitoring, while Azure also collects logs, and therefore it may be easier to understand context around the errors.
